### ISSUE TITLE
Error submitting sitemap index to: http://www.bing.com/ping....

### ISSUE THREAD

**Issue by celexus** [nystudio107/craft-seomatic#1043]
### Question
Some of my users are reporting an error when attempting to save a new entry via the CP. I see the following error in web.log: 
```
[nystudio107\seomatic\services\Sitemaps::submitSitemapForElement] Error submitting sitemap index to: http://www.bing.com/ping?sitemap=https%3A%2F%2Fwww.website.org.za%2Fsitemaps-1-section-articles-1-sitemap.xml - Client error: `POST http://www.bing.com/ping?sitemap=https%3A%2F%2Fwww.nsri.org.za%2Fsitemaps-1-section-articles-1-sitemap.xml` resulted in a `410 Gone` response
```
The following settings are set to on: 
Regenerate Sitemaps Automatically & Submit Sitemap Changes 

Is there an alternative way to Regenerate Sitemaps via a cron job, so that I can disable these settings & avoid my users getting stuck ?

**Comment by khalwat** [comment]
Looks like they deprecated that endpoint:

https://www.ctrl.blog/entry/sitemap-ping-indexnow.html

Addressed in: https://github.com/nystudio107/craft-seomatic/commit/25bd88688ed3995560f15b5560a99c953c21a306

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-seomatic": "dev-develop as 3.4.23”,
```
Then do a `composer clear-cache && composer update`

**Comment by KarlBishop** [comment]
I updated from SEOMatic 3.4.22 to 3.4.25 about 2 weeks ago but still see this kind of issue pop up in logs:

```
Error submitting sitemap index to: https://www.bing.com/webmaster/ping.aspx?sitemap=https%3A%2F%2Fwww.mysite.com%2Fsitemaps-1-section-mySection-1-sitemap.xml - Client error: `POST https://www.bing.com/webmaster/ping.aspx?sitemap=https%3A%2F%2Fwww.mysite.com%2Fsitemaps-1-section-mySection-1-sitemap.xml` resulted in a `400 Bad Request` response:
<html><body>Error occured while trying to submit the sitemap</body></html>
```

Are there additional steps I should have taken, following the plugin update, to fix this?

**Comment by khalwat** [comment]
I just tested it with that URL you listed, and it appeared to work. Perhaps it's some kind of a capacity issue, or they have a rate-limit on submissions?

**Comment by KarlBishop** [comment]
The failing URLs all seem to be of that form (different for different sections etc).

We shouldn't have a huge number of sitemaps based on our content.

We have:
- 19 sections
- 9 Category Groups
- 0 Commerce Product Types

...but I'm not sure *when* sitemaps are submitted to bing exactly i.e. what events would cause new submissions.

What I can tell you is:
- The last batch of errors occurred at 3:11 UTC this morning when I was the only CP user online
- There were 20 errors recorded, all for the same URL/section
- We have a nightly CRON job that imports entries from a JSON feed to the affected section (using the FeedMe plugin). The feed has 185 entries in it, so I guess if the sitemap was resubmitted to bing 185 times in quick succession, they might not like it 🤔

I can see other times in the logs when these types of errors occurred after seemingly innocent CP actions though, e.g. after someone created or edited a single entry. So that doesn't make such an obvious case for multiple submissions being triggered 🤷‍♂️

Do you think the FeedMe import would cause a new submission to bing once for every entry and so be a likely cause of a rate-limit issue?

**Comment by khalwat** [comment]
Yeah it's possible that the FeedMe is triggering it as you surmised.

In any event, Bing actually removed their public submission URL for changed pages, and the one I'm using is a semi-private one that apparently still works.

Because they are deprecating the use if it, I wouldn't be too concerned. I may even just remove it from SEOmatic if it remains troublesome.

**Comment by john-henry** [comment]
I think the Bing URL has finally given up the ghost. Getting a 410 for it now

[Bing stops accepting Sitemap pings](https://blogs.bing.com/webmaster/may-2022/Spring-cleaning-Removed-Bing-anonymous-sitemap-submission)

**Comment by khalwat** [comment]
Addressed in: <https://github.com/nystudio107/craft-seomatic/commit/9d7e7580e31352e60dbdc6d6f89a3b1ad419f171> & <https://github.com/nystudio107/craft-seomatic/commit/328c46e80392c45d3e720490bf69718b86a2ded2>

Craft CMS 3:

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-seomatic": "dev-develop as 3.4.31”,
```
Then do a `composer clear-cache && composer update`


Craft CMS 4:

…..

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-seomatic": "dev-develop-v4 as 4.0.1”,
```
Then do a `composer clear-cache && composer update`
