### ISSUE TITLE
Deprecation error: Treating element queries as arrays has been deprecated

### ISSUE THREAD

**Issue by philipboomy** [nystudio107/craft-seomatic#1185]
### Describe the bug

I am getting lots of these and I believe its Seomatic causing it. Is this a user error some how?

```
42 | Deprecation error: Treating element queries as arrays has been deprecated. Use exists() to determine if an element query will yield any results, or all() to fetch the results. Called from www.test.co.uk/vendor/craftcms/cms/src/elements/db/ElementQuery.php:618
-- | --
craft\elements\db\AssetQuery::offsetExists(0) Called from /www.test.co.uk/storage/runtime/compiled_templates/93/9325bb746612d995da0bbef98fc8fc1bd21d4dcfeb524f15517a5e0dbb6c3576.php:38
__TwigTemplate_dfc65669e77f8e152494b8e175e36a24202189eea123f7b45f1bf65f5c51492f::doDisplay(["object" => ["seomatic" => nystudio107\seomatic\variables\SeomaticVariable, "entry" => craft\elements\Entry], "seomatic" => nystudio107\seomatic\variables\SeomaticVariable, "entry" => craft\elements\Entry, "craft" => craft\web\twig\variables\CraftVariable, ...], []) Called from www.test.co.uk/vendor/twig/twig/src/Template.php:405
```

Line 38 is this here

```
echo craft\helpers\Template::attribute($this->env, $this->source, craft\helpers\Template::attribute($this->env, $this->source, ($context["seomatic"] ?? null), "helper", []), "socialTransform", [0 => (($__internal_compile_0 = craft\helpers\Template::attribute($this->env, $this->source, ($context["entry"] ?? null), "mainImage", [])) && is_array($__internal_compile_0) || $__internal_compile_0 instanceof ArrayAccess ? ($__internal_compile_0[0] ?? null) : null), 1 => "base", 2 => 1, 3 => "crop"], "method");
```

### Versions
- Plugin version: 3.4.36
- Craft version: 3.7.48

**Comment by khalwat** [comment]
Yep, aware of the issue, and it was solved for Craft 4

Interestingly, it may not be easily solvable for Craft 3. Stay tuned.

**Comment by khalwat** [comment]
Addressed in: https://github.com/nystudio107/craft-seomatic/commit/389b72ebacef9d20cf0ffa80d5a23d245d79015b

Craft CMS 3:

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-seomatic": "dev-develop as 3.4.37”,
```
Then do a `composer clear-cache && composer update`


Craft CMS 4:

…..

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-seomatic": "dev-develop-v4 as 4.0.7”,
```
Then do a `composer clear-cache && composer update`

**Comment by viesrood** [comment]
After doing the composer update, I still get the error messages, using Craft 3. Less than before, but still.

**Comment by khalwat** [comment]
It looks like they are undeprecating these messages anyway:

https://github.com/craftcms/cms/discussions/11625#discussioncomment-3173624

**Comment by darylknight** [comment]
Still seeing these deprecations on SEOmatic 3.4.37, but about to update to Craft 4.

**Comment by khalwat** [comment]
@darylknight again they are removing these deprecation errors in both Craft 3 and Craft 4 as per the above link and here:

https://github.com/craftcms/cms/issues/11597#issuecomment-1193331238

You will not see these errors on any version of Craft 4, however
