### ISSUE TITLE
Entry with SEO field type is always flagged 'changed'

### ISSUE THREAD

**Issue by ruudvdboom** [nystudio107/craft-seomatic#1239]
When using an SEO field with an entry the field is flagged as changed. Even if nothing has changed.
So the message "Showing your unsaved changes. [discard]" is allways shown

### To reproduce
Steps to reproduce the behaviour:
1. Create and add a SEO field to an entry (or other element type)
2. Open the entry in Craft
3. The page instantly shows the blue message and 'changed' lines

### Screenshots
<img width="497" alt="Screenshot 2022-11-15 at 16 37 42" src="https://user-images.githubusercontent.com/14345687/201961534-804d8c61-7f48-4389-99f1-5e1d26f66b35.png">

### Versions
- Plugin version: 4.0.13
- Craft version: 4.3.1

**Comment by khalwat** [comment]
I'm unable to replicate this, either when editing an existing entry or when creating a new entry. 

This is on Craft 4.3.1 & SEOmatic 4.0.13

Is it possible something else could be in the mix here?

**Comment by mikesnoeren** [comment]
I am experiencing the same issue on multiple projects, even when the SEOmatic field is the only field available within that section, simply opening the entry and clicking anywhere on the page renders all the seo fields as changed. To my best knowledge this issue started happening with one of the last SEOmatic or craft updates.

Setup:
Craft CMS 4.3.1 (Pro)
PHP version: 8.0.24
Operating system: Linux 5.10.109-0-virt (DDEV)
Database: MySQL 5.7.38
Image driver: Imagick 3.6.0 (ImageMagick 6.9.11-60)
Plugins and versions:
- Kint 3.1.0
- Navigation 2.0.11
- Redactor 3.0.2
- SEOmatic 4.0.13
- Super Table 3.0.5
- Typed link field 2.1.4

If you require any more info to debug this, feel free to let me know.

**Comment by turnstylerj** [comment]
We are also experiencing this updating from SEOmatic 4.0.11 to 4.0.13 (Craft 4.3.1) on multiple projects. Possibly a regression from this change in 4.0.12?

> Fixed an exception that could be thrown if you are using an SEO Settings field, by adding an explicit cast to (array) for checkbox field values that should be saved as an empty array [] but instead are saved as an empty string ''. Believed to be a regression in Craft 4.3 ([#1233](https://github.com/nystudio107/craft-seomatic/issues/1233)) ([#1231](https://github.com/nystudio107/craft-seomatic/issues/1231))

Setup details:
```
Craft CMS Pro 4.3.1
PHP 8.1.3
MySQL 8.0.28
Linux 4.15.0-163-generic

Amazon S3 2.0.1
Cloner 2.0.3
Colour Swatches 4.2.1
Control Panel CSS 2.5.0
Copy 2.2.0
Feed Me 5.0.4
Field Manager 3.0.4
ImageOptimize 4.0.2
Minify 4.0.0-beta.2
Neo 3.5.2
Redactor 3.0.2
Retour 4.1.5
Retcon 2.6.0
SEOmatic 4.0.11
```

**Comment by mihob** [comment]
Same issue here on every entry with seomatic fields:

Craft Pro 4.3.2

CP Field Inspect	1.4.4
Default Dashboard	2.0.0
Enforce password	2.0.0
Expanded Singles	2.0.0
Field Manager	    3.0.4
ImageOptimize	    4.0.2
Incognito Field	    1.3.0
LJ Range Slider	    4.0.1
Logs	            4.0.0
Neo	                3.5.2
Redactor	        3.0.2
Schedule	        0.4.0.1
Sentry SDK	        2.0.1
SEO & Social	    4.0.13

**Comment by khalwat** [comment]
@turnstylerj that's possible... but I think it may be a race condition with the JavaScript (which explains why I am not seeing it in my test case)

They are being loaded as modules now, so they aren't blocking... I think what's happening is the page loads, the browser takes a snapshot of the DOM's form state, and then the JavaScript modifies it, and thus it thinks things have "changed".

I'll be looking into this shortly.

**Comment by khalwat** [comment]
I'm still unable to reproduce this locally. Can anyone provide me with any additional steps to reproduce that might help?

The only commonality that I'm seeing is that everyone is on Craft 4.x and SEOmatic 4.0.13

**Comment by khalwat** [comment]
If you save an entry that shows that the SEOmatic field has changed, do you ever see the changed notice again?

**Comment by mihob** [comment]
As soon as you save an entry, the changed marker is gone. But as soon as you interact with the browser in any way (a mouse click is enough), the fields are marked as changed again and a revision is saved.

**Comment by khalwat** [comment]
Okay, I tracked down exactly what's wrong. It's very similar to what I suspected earlier in the thread.

What happens is the field outputs the form input HTML, and then because the JavaScript is loaded as a module now, it asynchronously loads and executes.

The JavaScript initializes some values and adds some properties to the form input HTML, which was fine when the JavaScript was loading synchronously... but now it happens AFTER the browser and/or Garish saves a snapshot of the form, which it uses to determine what has changed.

So then when you click on anything, Craft looks to see if any inputs have changed, and if so, highlights the changed inputs... which were "changed" by the initialization JavaScript that executed after the snapshot was taken.

**Comment by turnstylerj** [comment]
Sounds like you've got it tracked down, but just as an additional FYI, this was also introduced with SEOmatic 3.4.42 on a Craft 3.7.60 site of ours (not an issue with SEOmatic 3.4.41).

**Comment by khalwat** [comment]
@turnstylerj yep it'll affect the Craft 3 version too, because that was converted over to use ESM as well.

Knowing what is going wrong is more than half the problem... working on a fix shortly.

**Comment by khalwat** [comment]
This has been fixed.

Craft CMS 3:

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-seomatic": "dev-develop as 3.4.43”,
```
Then do a `composer clear-cache && composer update`

…..

Craft CMS 4:

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-seomatic": "dev-develop-v4 as 4.0.14”,
```
Then do a `composer clear-cache && composer update`

**Comment by khalwat** [comment]
This is released.

Craft 3: Version 3.4.43 -> https://github.com/nystudio107/craft-seomatic/releases/tag/3.4.43

Craft 4: Version 4.0.14 -> https://github.com/nystudio107/craft-seomatic/releases/tag/4.0.14

**Comment by carolineboeykens** [comment]
@khalwat , we are still seeing this issue. When we create a new entry, the bug is fixed. But when we try saving an existing entry where the bug occured, it is still not saving correctly.

Craft CMS: 4.3.3
SEO Matic: 4.0.15

**Comment by khalwat** [comment]
@carolineboeykens are you sure it is related to SEOmatic? What do you mean that it is not saving correctly?

**Comment by carolineboeykens** [comment]
![Screenshot 2022-12-01 at 08 30 06](https://user-images.githubusercontent.com/42932673/204992427-6fc46999-9fce-437e-be8b-6d236418b54c.png)

When we try to override the SEO description, it changes back to disabled after we save the entry:

![Screenshot 2022-12-01 at 08 30 17](https://user-images.githubusercontent.com/42932673/204992594-1eeb0ebb-17a6-49ea-922a-227bdd50ca02.png)

**Comment by khalwat** [comment]
@carolineboeykens That sounds like a bug that has been already fixed -- are you positive you're running the latest version of SEOmatic, and caches have been cleared, etc?

Does the same issue happen in local dev as well as on production?

I'm unable to reproduce this locally using the latest version of SEOmatic, which is `4.0.15`

**Comment by carolineboeykens** [comment]
Clearing the cache solved it! 🤦 
Feeling a bit dumb right now... Thank you for helping!
