### ISSUE TITLE
Ahrefs: Sitemap is not accessible

### ISSUE THREAD

**Issue by MatthiasBrodelet** [nystudio107/craft-seomatic#1437]
### Question
I recently started using the free version of Ahrefs and I often get a "Sitemap is not accessible" error on Craft CMS websites using SEOMatic. This probably is a Ahrefs issue and not an SEOMatic issue. Has anyone encountered this issue before?
Did I maybe configure SEOMatic incorrectly?
The weird thing is that when I force it to recrawl the site it usually finds the sitemap.

**Comment by khalwat** [comment]
It's possible that the sitemaps just aren't generated yet. If you then re-run Ahrefs, they should be generated, and it should work as expected.

**Comment by samuel-clara** [comment]
This happens for me randomly also after recrawling

**Comment by khalwat** [comment]
If the sitemaps are not generated yet, SEOmatic returns a `503` with a `retry-later` set to 30 seconds, as Google recommends.

So just re-crawl once the sitemaps have been generated, and away you go.

**Comment by MatthiasBrodelet** [comment]
At what point would the sitemap not be generated? Shouldn't there be a sitemap at all times? At worst it is an outdated one. Ahrefs crawls my websites once a month and the sitemaps are missing almost every time. I know they are there because when I open them manually it works. It's just confusing me :)

**Comment by khalwat** [comment]
Sitemaps are generated and cached when they are first accessed. So if you deploy the site for the first time, or you clear the caches, the sitemaps need to be generated.

They are generated in this manner because sitemaps can be huge, and take a very long time to generate, which can exceed the timeout inherent in most web requests.

When sitemaps need to be regenerated, it does work as you describe, in that it will serve up the old cached sitemap until the newly updated sitemap has been generated (the "stale-while-revalidate" pattern).

There is also a CLI command for generating the sitemaps, should you wish to use that: https://nystudio107.com/docs/seomatic/configuring/content-seo.html#sitemap-generation

**Comment by angelokeirsebilck** [comment]
I encounter the same issue. Site Audit in AHREFS gives an error that the sitemap is not accessible. Giving error 503 with message: Cannot download sitemap.

After checking the sitemap link, it does exist. So not sure what the problem is.

**Comment by khalwat** [comment]
@angelokeirsebilck please update to the latest version of SEOmatic, which should resolve this issue for you.

**Comment by angelokeirsebilck** [comment]
@khalwat still getting 503 errors in AHREFS that the sitemap cannot be downloaded. Weirdly enough the sitemaps do exist. Do you have an idea of what could cause this?

**Comment by khalwat** [comment]
@angelokeirsebilck Doesn't make any sense, that code no longer exists at all in SEOmatic.

My only guess is that AHREFS is using cached data in some manner.

**Comment by MatthiasBrodelet** [comment]
I have updated all of our Craft sites using Seomatic and still get this error randomly.
Every friday I get these reports from Ahrefs.
Some fridays a project might have no issues and the next one it will tell me that the sitemap is not accessible.

@khalwat You don't by any chance have connections at Ahrefs to figure this out? :)
I'm pretty sure the issue must be on their end.

**Comment by samuel-clara** [comment]
Same here!

**Comment by angelokeirsebilck** [comment]
Also still happening here. Sometimes it throws and error, sometimes not. Most of the time it does tho. In AHREFS the error says it is a curl error 23.

**Comment by khalwat** [comment]
Alright let me re-examine the code.

**Comment by khalwat** [comment]
So I have to eat some crow here; I discovered that not all of the vestigal code had indeed been removed, despite my claims above. Sorry about that.

It's still unclear to me how this code path could ever be reached, but I've done an exhaustive search of the codebase and SEOmatic is now never returning a `503` error. You can see the changes in the commits above.

So if you want to test out the update below, you can get it up and running... and if we still see a `503` error, it's definitely from some kind of cached data on AHREFs side of things.

Unfortunately, I do not have any contacts at AHREFs that could help out here.

Craft CMS 3:

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-seomatic": "dev-develop as 3.5.4”,
```
Then do a `composer clear-cache && composer update`

…..

Craft CMS 4:

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-seomatic": "dev-develop-v4 as 4.1.4”,
```
Then do a `composer clear-cache && composer update`

…..

Craft CMS 5:

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-seomatic": "dev-develop-v5 as 5.1.4”,
```
Then do a `composer clear-cache && composer update`
