### ISSUE TITLE
News Sitemap Broken

### ISSUE THREAD

**Issue by tibbis** [nystudio107/craft-seomatic#1551]
### Describe the bug
The News sitemap feature seems broken, the News title is not saved as it disappears after save. Also I cant find the <news:news> sitemap anywhere when inspecting sitemap.  

### To reproduce
Steps to reproduce the behaviour:
1. Go to seomatic content settings, select a section
2. Click on sitemap
3. Enable News Sitemap and set a title
4. Save and check results

### Expected behaviour
The title text should be saved and I should see a news sitemap.

### Screenshots
<img width="1237" alt="Screenshot 2024-12-19 at 14 00 12" src="https://github.com/user-attachments/assets/08c08d38-f36e-46e1-9571-c7a15af8163f" />

### Versions
- Plugin version: 5.1.7
- Craft version: 5.5.7

**Comment by khalwat** [comment]
So the good news is, the News Sitemap feature is working properly (I'll explain more in my next post), the issue was just a visual glitch where the **News Publication Name** was not displayed on the frontend.

It's fixed in the above commits.

Craft CMS 3:

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-seomatic": "dev-develop as 3.5.9”,
```
Then do a `composer clear-cache && composer update`

…..

Craft CMS 4:

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-seomatic": "dev-develop-v4 as 4.1.8”,
```
Then do a `composer clear-cache && composer update`

…..

Craft CMS 5:

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-seomatic": "dev-develop-v5 as 5.1.8”,
```
Then do a `composer clear-cache && composer update`

**Comment by khalwat** [comment]
So the visual glitch aside, the News Sitemap is indeed working properly, if you choose **View Source** on a Section's sitemap where it is enabled, you'll see this in the XML:

```xml
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" xmlns:image="http://www.google.com/schemas/sitemap-image/1.1" xmlns:video="http://www.google.com/schemas/sitemap-video/1.1" xmlns:xhtml="http://www.w3.org/1999/xhtml" xmlns:news="http://www.google.com/schemas/sitemap-news/0.9">
```

Note the `xmlns:news="http://www.google.com/schemas/sitemap-news/0.9"`

You might _not_ see anything else, though, because as per Google's spec, only articles that are less than 2 days old should ever be displayed:

> Only include recent URLs for articles that were created in the last two days. Once the articles are older than two days, either remove those URLs from the news sitemap or remove the <news:news> metadata in your sitemap from the older URLs.

ref: https://developers.google.com/search/docs/crawling-indexing/sitemaps/news-sitemap

Assuming you have articles that are less than 2 days old, they will be displayed in the XML like this:

```xml
  <url>
    <loc>http://plugindev.local:8004/blog/my-first-blog</loc>
    <lastmod>2024-12-19T11:30:18-05:00</lastmod>
    <changefreq>weekly</changefreq>
    <priority>0.5</priority>
    <xhtml:link rel="alternate" hreflang="x-default" href="http://plugindev.local:8004/blog/my-first-blog"/>
    <xhtml:link rel="alternate" hreflang="en-us" href="http://plugindev.local:8004/blog/my-first-blog"/>
    <xhtml:link rel="alternate" hreflang="es" href="http://plugindev.local:8004/es/blog/my-first-blog"/>
    <news:news>
      <news:publication>
        <news:name>WOOF</news:name>
        <news:language>en</news:language>
      </news:publication>
      <news:publication_date>2024-12-19T11:30:18-05:00</news:publication_date>
      <news:title>My first blog</news:title>
    </news:news>
  </url>
```

Note the extra `<news:` items.

**Comment by tibbis** [comment]
Thanks for the info! I did try with posts earlier than 2 days but I'm still not seeing the `<news:news>` part... Any other settings that are crucial for it to work? 

I do see the first sitemap-news part yes.


`<?xml version="1.0" encoding="UTF-8"?><?xml-stylesheet type="text/xsl" href="sitemap.xsl"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" xmlns:xhtml="http://www.w3.org/1999/xhtml" xmlns:news="http://www.google.com/schemas/sitemap-news/0.9"><url><loc>https://listecasinoenligne.ddev.site/news/test</loc><lastmod>2024-12-21T09:31:00+01:00</lastmod><changefreq>weekly</changefreq><priority>0.9</priority><xhtml:link rel="alternate" hreflang="fr" href="https://listecasinoenligne.ddev.site/news/test" /></url><url><loc>https://listecasinoenligne.ddev.site/news/7-millions-pour-une-licence-de-casino-en-ligne-en-italie</loc><lastmod>2024-12-18T16:17:40+01:00</lastmod><changefreq>weekly</changefreq><priority>0.9</priority><xhtml:link rel="alternate" hreflang="fr" href="https://listecasinoenligne.ddev.site/news/7-millions-pour-une-licence-de-casino-en-ligne-en-italie" /></url><url><loc>https://listecasinoenligne.ddev.site/news/les-casinos-en-ligne-explosent-au-danemark</loc><lastmod>2024-12-18T16:02:13+01:00</lastmod><changefreq>weekly</changefreq><priority>0.9</priority><xhtml:link rel="alternate" hreflang="fr" href="https://listecasinoenligne.ddev.site/news/les-casinos-en-ligne-explosent-au-danemark" /></url><url><loc>https://listecasinoenligne.ddev.site/news/casinos-en-ligne-neerlandais-le-grand-chambardement-pour-2025</loc><lastmod>2024-12-18T15:28:05+01:00</lastmod><changefreq>weekly</changefreq><priority>0.9</priority><xhtml:link rel="alternate" hreflang="fr" href="https://listecasinoenligne.ddev.site/news/casinos-en-ligne-neerlandais-le-grand-chambardement-pour-2025" /></url></urlset>`

**Comment by tibbis** [comment]
Would you mind helping me with the missing news: items? I must have missed some setting, I really cant get it to add the news sitemap part. 
The page: https://listecasinoenligne.com/news

**Comment by khalwat** [comment]
Interesting, part of the implementation did not make it into the Craft 5 version of the plugin (but operates as expected for the Craft 4 & Craft 3 versions).

Fixed in the above commit.

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-seomatic": "dev-develop-v5 as 5.1.9”,
```
Then do a `composer clear-cache && composer update`
