### ISSUE TITLE
`fb:profile_id` is converted to a number

### ISSUE THREAD

**Issue by XhmikosR** [nystudio107/craft-seomatic#190]
Happens only in my local environment, regardless if I'm in devMode though.

For example, I enter `123456789123456` as Facebook Profile ID, and after I click save it becomes `1.2345678912346E+14`

I'm using v3.1.8 with Craft CMS Pro 3.0.18.

**Comment by khalwat** [comment]
That's really odd. I tried it here, and it saves it properly:

<img width="315" alt="google chromescreensnapz208" src="https://user-images.githubusercontent.com/7570798/43689749-f483ee12-98cc-11e8-92dc-adbd19dd41b1.png">

So what is particular about your local environment? PHP version? Web server version/type?

**Comment by khalwat** [comment]
Addressed in https://github.com/nystudio107/craft-seomatic/commit/a9b67839387fa633289df66f48f104dc8f1771ea

**Comment by XhmikosR** [comment]
@khalwat Nope, this is not fixed for me with 3.1.11. :/

**Comment by XhmikosR** [comment]
@khalwat: this still happens for me on my dev machine, so please open this issue again.

**Comment by khalwat** [comment]
This is very likely something localized with your dev machine; you can try this out by changing the composer semver to `dev-develop`: https://github.com/nystudio107/craft-seomatic/commit/d1ce7defb1c5a5c8f9621d273f6ce11f1f091eba

But there have been known bugs in various versions of PHP regarding `json_encode` -- I can't fix it if I can't reproduce it. You'll need to provide information on your local dev environment, including the exact versions of what you're running.

My guess is that it's likely that updating your PHP version would take care of this.

**Comment by XhmikosR** [comment]
@khalwat: my PHP version is the latest 7.2.7 already. The issue still happens with dev-develop.

But if I change PHP's `precision` to 16 then it shows right. What I don't understand is that on my production server precision is set to 14 and it works fine there.

If I search the database, it seems the correct value is there anyway.

**Comment by khalwat** [comment]
I don't know what the answer is; but again, look for differences between your local dev setup (where it's not working) and your live production server/staging server, where it does.

I'm explicitly typecasting both of these variables as `(string)` (which shouldn't even be necessary). so I'm not sure why it is doing that, but it appears to be a cosmetic error. If the value is display correctly in the db, then my guess would be potentially an issue with Yii2/Twig or a bug in that specific version of PHP that you're running.

It's either that, or some explicit change in that most recent version of PHP that requires some kind of type coercing that isn't being done.

**Comment by XhmikosR** [comment]
No, it's not output correctly in the templates either.

**Comment by khalwat** [comment]
...which again would lead me to believe that since the data is correct in the db, the issue is likely somewhere between pulling it from the db and displaying it.

Things in that pipeline:

1) PHP
2) Twig
3) Yii2
4) Craft CMS
5) SEOmatic

I have done everything I can do to try to ensure that I'm explicitly converting types in SEOmatic. Since you're seeing different behavior on your local dev setup than you are on your production and server environments, and the SEOmatic code is the same on both, I'm going to assume the problem lies elsewhere in the chain.

**Comment by khalwat** [comment]
So this ends up being what I expected, in that it's baked into Yii2. I'm using Yii2's `Json::decode` which ends up calling PHP's `json_decode` which by default converts large integers to scientific notation floats.

This behavior can be overridden via `JSON_BIGINT_AS_STRING` but unfortunately, the Yii2 method does not allow me to pass down options to it, so I ended up having to subclass it, and implement the functionality on my own. Fixed in: https://github.com/nystudio107/craft-seomatic/commit/146fb15bd1da58a5f1e210dbd2e1b8bab0e7aaec

**Comment by XhmikosR** [comment]
Thanks!

**Comment by khalwat** [comment]
This is due to a combination of your PHP version/environment, and just how Yii2 assumes JSON should be encoded/decoded.

**Comment by XhmikosR** [comment]
I haven't tried this yet, BTW, but judging from the fix this should do it. I will be able to confirm when the new version is out.

**Comment by khalwat** [comment]
I was able to reproduce it by putting in a massive number like `123456789123456123456789123456123456789123456` and so was able to validate the fix.
