### ISSUE TITLE
Changes to field values are not saving

### ISSUE THREAD

**Issue by jsunsawyer** [nystudio107/craft-seomatic#54]
Updated to 3.0.0-beta.20 to add the new SEO field for a few post types. I can no longer get any changes to fields to save. Tested locally and on staging.

**Comment by jsunsawyer** [comment]
SEO Field values seem to be saving. Just nothing from the SEO tab in craft. (Global SEO, Content SEO, etc)

**Comment by khalwat** [comment]
Anything in your error logs of note?

**Comment by jsunsawyer** [comment]
Not that I have seen.

**Comment by khalwat** [comment]
So you aren't able to save _anything_ in the Global SEO, Content SEO, Site Settings, or Plugin Settings tabs?

**Comment by jsunsawyer** [comment]
Exactly. Trying to update the `SEO Description Source` field content in `Global SEO`, which my homepage is set to use, fails to change the field content on save and does not render on the front-end when I view page source.

Edit: The clarify, the updated content does not render. The value that I had before the plugin update is what displays when I view source.

**Comment by khalwat** [comment]
Right, I'm suspecting there's a model validation error which is causing it to not save; can you check your logs to see if you find anything? The Yii2 debugger should let you search on `seomatic` to find any related errors.

**Comment by khalwat** [comment]
For sure uninstalling and re-installing the plugin will fix this, but you will lose any data you've already added, which is probably not good.

I suspect something went wrong with the meta bundle update.

**Comment by jsunsawyer** [comment]
Uninstalled/reinstalled and am able to save changes now.

**Comment by jsunsawyer** [comment]
While re-adding content, I ran into the same issue in Site Settings and Tracking Scripts. Both places don't save my changes after any edits.

This only happens on my local install. On staging, I'm able to save fields here.

**Comment by mikestecker** [comment]
Noticed this happening today. I went to go look at my analytics data and noticed it was empty, then when I went to check my tracking settings I noticed it won't save them. This is happening on my production server. I can turn the light switch on, make changes but once I click save, it reverts to being switched off and the fields are emptied.

**Comment by khalwat** [comment]
Would either of you be able to get a db dump to me? andrew@nystudio107.com or you can send it via Slack.

**Comment by khalwat** [comment]
Figured it out by doing some on-site debugging. It’s what I thought, just a silly validation error

**Comment by khalwat** [comment]
Fixed in https://github.com/nystudio107/craft-seomatic/commit/7bba410c7ef04e384001c1687e2f8e9f3ffe7e5e

**Comment by richardcalahan** [comment]
This is still happening despite running the latest version (3.0.5) including the fix mentioned above. Setting changes in Content SEO are not saving. 

Tried clearing cache, uninstalling/reinstalling. Issue persists.

**Comment by khalwat** [comment]
This is a different issue @richardcalahan I'll open one for you

**Comment by khalwat** [comment]
@richardcalahan https://github.com/nystudio107/craft-seomatic/issues/93
