### ISSUE TITLE
SEO Preview in SEO Field is incorrect after changing the value of a description

### ISSUE THREAD

**Issue by jsunsawyer** [nystudio107/craft-seomatic#55]
I am allowing users to set overrides on some post types for **SEO Description Source** and **SEO Image Source**.

**SEO Description Source** pulls from an **Excerpt** field by default.

Before changing anything, the correct description is displayed, pulling from excerpt if one is set. When you change the description on an entry via the SEO field, the description shows the Global SEO default. Reverting the change keeps the incorrect Global SEO value.

All values are correct when rendering the template and viewing source.

Also, a **Use Default** option for SEO Fields (that is set as default) may be valuable to provide additional clarity for the user. A blank field looks like it requires attention.

**Comment by khalwat** [comment]
Okay, so you're saying it's just a visual issue with the preview that's being displayed in the Field itself (not in the sidebar) after you change the field value?

**Comment by jsunsawyer** [comment]
This affects both the field preview and sidebar preview the same way.

Tested a few more scenarios. It seems that any entry, even ones without the SEO Field, when re-saved after the most recent update, replace the correct preview content with the `Global SEO` defaults.

**Comment by jsunsawyer** [comment]
After an uninstall/reinstall, this issue persists. (Fixed a different issue for me)

**Comment by john-henry** [comment]
Issue is happening for me also with both the field preview and sidebar preview

 3.0.0-beta.21 and Craft CMS 3.0.1

A video is probably easier http://cloud.johnhenry.ie/qks2

**Comment by khalwat** [comment]
Same as: https://github.com/nystudio107/craft-seomatic/issues/65

**Comment by khalwat** [comment]
Fixed in https://github.com/nystudio107/craft-seomatic/commit/dd8181058cd279b86af2f605894dc37ab159e919

**Comment by jsunsawyer** [comment]
@khalwat Just updated to 3.0.0-beta.22 and still having issues.

When I save an entry that has an SEO Field, the Global SEO description content is used for the preview. Refreshing the page displays correct information once again.

Note: Using `cmd + s` to save. Also happens if you use the save dropdown `Save and continue editing`.

**Comment by khalwat** [comment]
Fixed in https://github.com/nystudio107/craft-seomatic/commit/9e27390c523b553fd9e2d10419af7ed8ee5bdada
