### ISSUE TITLE
SEO field image transform outputting twig code

### ISSUE THREAD

**Issue by mikestecker** [nystudio107/craft-seomatic#64]
I added a SEO field to my client's news section so they can override the primary image with custom ones in some use cases but I'm getting twig code on the output.

View the source for this URL to see it happening: https://cityofmarion.in.gov/news-events/few-tickets-remaining-for-daddy-daughter-dance

```
<meta content="{seomatic.helper.socialTransform(2523, &quot;facebook&quot;, )}" property="og:image">
<meta name="twitter:image" content="{seomatic.helper.socialTransform(2523, &quot;twitter-summary&quot;, )}">
```

**Comment by khalwat** [comment]
This one is very interesting to me, as it's pretty unfathomable how it could happen... which it clearly is. So that should be fun to look into :)

**Comment by khalwat** [comment]
Not to unfathomable after all. Fixed in https://github.com/nystudio107/craft-seomatic/commit/d42e52b1236bb27d25a9f2da8b51c6cf15a22d72

**Comment by mikestecker** [comment]
@khalwat Still seeing the bug. I updated and deployed beta 22 this morning, cleared caches, even re-saved an entry to test but I'm still seeing the twig code at this URL: https://cityofmarion.in.gov/news-events/few-tickets-remaining-for-daddy-daughter-dance

**Comment by khalwat** [comment]
Try re-saving the Section. It should be fixed.

**Comment by mikestecker** [comment]
Hmm tried that. I tried re-saving the whole section, I tried re-saving the entry type settings, re-saving the entry, even re-saving the SEOmatic settings for the section as well. Nothing seems to fix it.

**Comment by khalwat** [comment]
So this ends up being another bug, totally unrelated... but quite silly. :)

Basically, when coming from a Field, the `siteId` wasn't set, which would cause it to render invalid Twig:

```
{seomatic.helper.socialTransform(2523, "twitter-summary", )}
```

(note the comma with no parameter after it).

Which would cause it to not render. Fixed in https://github.com/nystudio107/craft-seomatic/commit/d2bce4d008e503da31767be5ac496fb74542edd8
