### ISSUE TITLE
[FR] Remove trailing slashes to root site URLs

### ISSUE THREAD

**Issue by khalwat** [nystudio107/craft-seomatic#717]
If the `addTrailingSlashesToUrls ` general config setting isn't set, remove trailing slashes such that this:

```html
<link href="https://fedex.localhost/en-gb/" rel="canonical">
<link href="https://fedex.localhost/en-gb/" rel="home">
```

becomes this:

```html
<link href="https://fedex.localhost/en-gb" rel="canonical">
<link href="https://fedex.localhost/en-gb" rel="home">
```

Note that Craft's built-in `siteUrl()` function does not mirror this functionality: 

https://github.com/craftcms/cms/issues/5675

**Comment by khalwat** [comment]
Implemented via https://github.com/nystudio107/craft-seomatic/commit/dae2c96718959c6b57945f5293cc34da3d2584ae

**Comment by karensg** [comment]
If I am not mistaken, the sitemap still has this issue.

**Comment by khalwat** [comment]
@karensg addressed in https://github.com/nystudio107/craft-seomatic/commit/20aabb5c3a5c3ddd5b53f85b9a6c38ad7ce242c5

**Comment by karensg** [comment]
Thanks! Just updated to the newest version. The issue still persists in the hreflang in the sitemap though

**Comment by khalwat** [comment]
@karensg please double-check that it isn't just cached?

**Comment by karensg** [comment]
Yes, I did, here is an example: <removed>

**Comment by khalwat** [comment]
I see. It's doing it for the `<loc>` but not the `alternate`. Fixed in https://github.com/nystudio107/craft-seomatic/commit/c671ac8a291e393994e8a9d640fa4f6b3a8cd5d8

**Comment by karensg** [comment]
Hi, sorry. I believe there are 3 more places where it goes wrong:
- og:url
- ld+json mainEntityOfPage
- ld+json BreadcrumbList

**Comment by khalwat** [comment]
@karensg can you show me examples of these 3 please?

**Comment by karensg** [comment]
Here it is: <removed>

**Comment by karensg** [comment]
Hey @khalwat, just checking in about these minor bugs.

**Comment by khalwat** [comment]
I just traced through the code, and it looks to me like it should be adding a trailing `/` to the `og:url` -- the default setting for the `og:url` is:

```
            'og:url'              => [
                'charset'   => '',
                'content'   => '{seomatic.meta.canonicalUrl}',
                'httpEquiv' => '',
                'name'      => '',
                'property'  => 'og:url',
            ],
```

...and the default setting for the `seomatic.meta.canonicalUrl` variable is:

```
        'canonicalUrl'            => '{seomatic.helper.safeCanonicalUrl()}',
```

and that function does add trailing slashes as needed. 

Can you tell me what you have your `canonicalUrl` set to?

**Comment by karensg** [comment]
Hey,

Thanks for your help, really appreciate it. It was `{entry.url}` in CMS (nothing in code). Probably the old default. I changed it for the homepage for all languages to `{seomatic.helper.safeCanonicalUrl()}` and it indeed solved 2 issues.
The last issue is in ld+json BreadcrumbList. See [staging](https://removed.com/en). This one was not fixed by this change.

Karens

**Comment by khalwat** [comment]
Can you paste in an example of the breadcrumbs from a page? I just want to see all of the URLs. Thanks!

**Comment by karensg** [comment]
You can see it when you view the source [of the page](https://staging.client.com/):
```
{"@type":"BreadcrumbList","description":"Breadcrumbs list","itemListElement":[{"@type":"ListItem","item":"https://staging.client.com/en/","name":"The product of Client","position":1}],"name":"Breadcrumbs"}]}
```

Same problem on any other page

**Comment by khalwat** [comment]
Addressed in https://github.com/nystudio107/craft-seomatic/commit/21d49b9d2dc839f7d272765e694241cbdba27a0b

**Comment by russback** [comment]
@khalwat just had this pop up on audit of a site using v5.1.5.

With `addTrailingSlashesToUrls` set to `true`:

```html
<meta content="https://domain.ddev.site/" property="og:url">
<link href="https://domain.ddev.site/" rel="canonical">
<link href="https://domain.ddev.site/" rel="home">
```

But with `addTrailingSlashesToUrls` set to `false`, `og:url` still has the trailing slash:

```html
<meta content="https://domain.ddev.site/" property="og:url">
<link href="https://domain.ddev.site" rel="canonical">
<link href="https://domain.ddev.site" rel="home">
```

This is after cache cleared.

Workaround with this removes the slash but ideally this wouldn't be required?

```twig
{% do seomatic.tag.get('og:url').content(getenv('PRIMARY_SITE_URL')) %}
```

**Comment by khalwat** [comment]
@russback assuming this is for an entry page, that resolves to `{{ entry.url }}` -- try putting that Twig code on the entry page, and I think you'll see it'll match

If so, that means Craft is generating the URL for that entry with the trailing slash on it...

**Comment by russback** [comment]
This was on the home page, which will be a single entry. Craft adding a slash when `addTrailingSlashesToUrls` is false though - seems like a bug or at least confusing behaviour?

Settled for this in the end on the layout template:

```twig
{% if entry is defined and entry %}
	{% set currentUrl = entry.url | trim('/', 'right') %}
	{% do seomatic.meta.canonicalUrl(currentUrl) %}
{% endif %}
```

**Comment by khalwat** [comment]
On that page, can you do:

```
{{ seomatic.meta.canonicalUrl }}
```

...and show me what it outputs?

**Comment by russback** [comment]
Without any changes it looks like this:

`{{ entry.url }}`

And with the change I mentioned where I set it from the trimmed entry URL:

`https://mysite.ddev.site`

In SEO settings, Global canonical is set as `{{ seomatic.helper.safeCanonicalUrl() }}` and Content canonical for the home page is `{{ entry.url }}`. 

If I remove that canonical setting at the **Content** level, the **Global** value displays and I no longer need that trim, so this was a config issue in the end.

**Comment by khalwat** [comment]
Yep, config issue makes sense.

**Comment by tibbis** [comment]
> I see. It's doing it for the `<loc>` but not the `alternate`. Fixed in [c671ac8](https://github.com/nystudio107/craft-seomatic/commit/c671ac8a291e393994e8a9d640fa4f6b3a8cd5d8)

Seems like this issue is back for alternate urls, trailing slash is added to home page singles that has a subdirectory like: `example.com/de` becomes `example.com/de/` as entry.url and alternate url. The canonical url can be overridden in config but not the alternate url for sitemaps. It is a craft cms issue originally. 

Any suggested workaround I missed?

**Comment by khalwat** [comment]
@tibbis what version of Craft and what version of SEOmatic are we talking about?

**Comment by tibbis** [comment]
> @tibbis what version of Craft and what version of SEOmatic are we talking about?

Craft Pro 5.5.7
SEOmatic 5.1.8

**Comment by khalwat** [comment]
Show me how your site URLs are defined. Do they contain a trailing slash in them?

Go to CP -> Settings -> Sites and look at the **Base URL** that is displayed there.

Or if you have defined it, also go to CP -> Settings -> Sections, and click on the Section in question and show me what you have listed there for the **URI**

**Comment by tibbis** [comment]
> Show me how your site URLs are defined. Do they contain a trailing slash in them?
> 
> Go to CP -> Settings -> Sites and look at the **Base URL** that is displayed there.
> 
> Or if you have defined it, also go to CP -> Settings -> Sections, and click on the Section in question and show me what you have listed there for the **URI**

<img width="887" alt="image" src="https://github.com/user-attachments/assets/b501ee52-5edc-4e29-88d6-ea6aa48d4dac" />
<img width="733" alt="Screenshot 2024-12-26 at 23 00 16" src="https://github.com/user-attachments/assets/0780c160-6ebc-4129-905e-fea786fb0e97" />
This is a known issue that craft is not respecting addTrailingSlashesToUrls(false) so the problem comes from this. But seems like there is a workaround?

It's the home page single section so no URI is shown.

**Comment by khalwat** [comment]
Well, it might be a misunderstanding, too. `addTrailingSlashesToUrls` will add slashes to the end of a URL, but it will not remove them.

So if the URL has a trailing slash, it won't remove it. I checked the code, and SEOmatic is just asking the element what its URL is, and using that. So yes, the "problem" is upstream.

But I'm not convinced it's actually a problem.

If you really want the URL to not have a trailing slash, then your URL to the index page of the site should be:

`http://example.com/es/index` -- the shorthand `http://example.com/es/` causes your webserver to look for an `index.html` file (or in Craft's case, an `index.twig` or whatever you're named that section's template.

**Comment by tibbis** [comment]
Here is the open issue planned for v6 https://github.com/craftcms/cms/issues/5675

But are you saying you don’t have this issue with subdirectory siteurl?

**Comment by khalwat** [comment]
While I think this is largely as non-issue, and will not affect SEO in any measurable way, I've implemented it in SEOmatic.

Craft CMS 3:

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-seomatic": "dev-develop as 3.5.10”,
```
Then do a `composer clear-cache && composer update`

…..

Craft CMS 4:

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-seomatic": "dev-develop-v4 as 4.1.9”,
```
Then do a `composer clear-cache && composer update`

…..

Craft CMS 5:

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-seomatic": "dev-develop-v5 as 5.1.9”,
```
Then do a `composer clear-cache && composer update`
