### ISSUE TITLE
Setting robots value by entry type doesn't work

### ISSUE THREAD

**Issue by khalwat** [nystudio107/craft-seomatic#929]
in https://github.com/nystudio107/craft-seomatic/issues/814#issuecomment-881547260 @kaitlyn-higgins wrote:

@khalwat I'm experiencing the same issue as @masonry47 above with sitemaps. Disabling sitemaps for one entry type disables for both & vice versa - leading to either all of the entries for both types coming through, or a 404 page.

I have ensured that I select the entry type from the dropdown before making any changes or saving it so that the typeId URL param is being populated, and confirmed that the typeId is changing when I toggle between the two entry types.

The odd thing is (and I'm not sure if this is consistent with what the others have faced or not), when I go back into the section and check the sitemap settings, they are both correctly toggled (one on, one off) - despite the sitemap not respecting that selection.

I'm running version 3.3.44 so it seems that somehow this bug has creeped back up between 3.3.37 and 3.3.44.

Let me know if you need any other details, or would like me to send a screen recording so you can see the issue in action.

And that's correct. I have toggled 'Sitemap Enabled' to 'on' for Internal News entries, and 'Sitemap Enabled' to 'off' for External News entries, and saved both. If I save the Internal (sitemap on) settings last, the sitemap will be generated for both Internal and External entries. If I save the External (sitemap off) settings last, the sitemap page will return a 404 (so no entries from either entry type are being sitemapped).

**Comment by khalwat** [comment]
Addressed in: https://github.com/nystudio107/craft-seomatic/commit/5327dc27624c19a67b8a1a2774919b36f58fb30a

@kaitlyn-higgins can you give this a whirl?

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-seomatic": "dev-develop as 3.3.45”,
```
Then do a `composer clear-cache && composer update`

**Comment by kaitlyn-higgins** [comment]
@khalwat Thanks for looking into this and creating a new ticket. I tried updating the package and clearing the cache as you suggested, but it's still not working as expected.

Now the External News entry type sitemap settings are not being respected at all - they're just not being indexed, whether they're enabled or not.

For example, if I have both internal and external sitemaps enabled, I'm only getting 51 urls when I should be getting something like 191. Disabling external news sitemaps doesn't change that number at all.

If I disable internal news sitemaps but have external news sitemaps enabled, I'm getting 404'd - whereas I should be getting a sitemap with the external news URLs.

Since it seems to only be indexing Internal News URLs, it may be helpful to know that Internal News is the first entry type.

**Comment by khalwat** [comment]
@kaitlyn-higgins how long ago did you do that? I just pushed some new changes 2 hours ago that fix some issues with it

Go to each Entry Type and make sure the Sitemap settings are the way you want them to be, and then click on Save.

**Comment by kaitlyn-higgins** [comment]
@khalwat Just peeped your commit number 929 and figured out why it wasn't working after the update - robots for External News entry type was set to None, so user error on my part. If robots are set to all, the sitemap preferences are being respected for both entry types. 

You can mark as solved. Thanks again! :)

**Comment by khalwat** [comment]
Glad you have it all sorted!
