### ISSUE TITLE
SEO settings field - image overrride not working

### ISSUE THREAD

**Issue by wihodges** [nystudio107/craft-seomatic#962]
### Describe the bug
When toggling on the SEO image override, the entry is not updated with the specific SEO image.  

### Expected behaviour
The title and description fields work as expected. Change title and save post and the SEO preview confirms the update. Change the SEO image and save, and the preview does not update.

So I checked another separate site with all the recent updates and it does not work either.

### Versions
- Plugin version: 3.4.3 and 3.4.4
- Craft version: 3.7.10

**Comment by lenvanessen** [comment]
@khalwat I can confirm, definitly broken. 
![Schermafbeelding 2021-08-27 om 10 29 46](https://user-images.githubusercontent.com/23024452/131097919-c8ff55b2-40da-4f06-944c-d0653f36156b.png)
![Schermafbeelding 2021-08-27 om 10 29 41](https://user-images.githubusercontent.com/23024452/131097967-832129e8-5b56-4a5c-89b5-0af75df4a66e.png)

**Comment by khalwat** [comment]
Addressed in: https://github.com/nystudio107/craft-seomatic/commit/d3cd9e15cc8b529d23bc73a4635c46e3a34d651f

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-seomatic": "dev-develop as 3.4.5”,
```
Then do a `composer clear-cache && composer update`

**Comment by justinholtweb** [comment]
I can confirm the preview works with this fix applied on v3.4.6 but I am still seeing incorrect meta data in the actual Twitter and Facebook tab-previews. Attaching some screenshots to show this:

First - here is the General tab showing the Title, description, and meta image overides:
![General-tab](https://user-images.githubusercontent.com/295903/132394395-b3cbbe82-db23-4f48-8263-872fde6cdc4b.jpg)

Then, here are the Twitter and Facebook tabs showing outdated share previews. Both are set by entry default to pull from SEO values:
![Twitter-tab](https://user-images.githubusercontent.com/295903/132394526-9caea149-d4c9-4475-b431-a0f2ce8bac37.jpg)
![Facebook-tab](https://user-images.githubusercontent.com/295903/132394537-ef0d7605-22e8-4b3b-bf9f-5e49918334a5.jpg)

Preview in Craft actually shows correct metadata as expected! Hurray! 
![Screen Shot 2021-09-07 at 2 03 15 PM](https://user-images.githubusercontent.com/295903/132394771-ebceb26a-dcb2-46c9-8fe0-01c8d4264ceb.jpg)


#Versions
Plugin version: 3.4.6
Craft version: 3.6.3

**Comment by khalwat** [comment]
That's really curious @justinholtweb -- I think this is probably unrelated to this issue, however.

Have you tried re-saving your Content SEO settings for that section? Also have you cleared caches?

**Comment by justinholtweb** [comment]
@khalwat I will try doing both of those this afternoon and report back. It's a minor inconvenience really, I've since instructed the client to use Preview for this when they need to see the social previews. Nonetheless I will report back on if either of those fix the issue I am seeing. 

Thanks for the quick reply!

**Comment by khalwat** [comment]
We definitely want to get this fixed if we can pin down what is going wrong! lmk

**Comment by khalwat** [comment]
I'm trying to reproduce this, but don't seem to be able to... am I missing something in my setup here?

<img width="1282" alt="Screen Shot 2021-09-07 at 3 40 54 PM" src="https://user-images.githubusercontent.com/7570798/132401643-c654d4e6-290d-4936-9a9f-5f366ec9923e.png">
<img width="1282" alt="Screen Shot 2021-09-07 at 3 40 49 PM" src="https://user-images.githubusercontent.com/7570798/132401651-e6bafd4b-8445-45f1-8012-2f0e842a53cf.png">

**Comment by justinholtweb** [comment]
@khalwat Did a test on the clients staging/remote with a fresh post after updating SEOMatic to 3.4.6. I was able to reproduce the incorrect tab-preview but ONLY when the post was still in unpublished draft status. Once I published the post live the tab-previews updated with correct post-level SEO field value override data! See if you can recreate with a fresh post when it's only in the draft status.

**Comment by khalwat** [comment]
Yeah @justinholtweb this is indeed an entirely unrelated issue. I have created a new issue where you can add your comments if you like: https://github.com/nystudio107/craft-seomatic/issues/972
